### ISSUE TITLE
Experiment with progressive rendering

### ISSUE THREAD

**Issue by nonmetalhail** [PredixDev/px-vis-parallel-coordinates#12]
Experiment with progressive rendering and see if we can get it to work well.

Current stub takes too long as it only draws 1 line every "1ms". Should try to make it draw larger sets of data over a timeframe.

Also look into making not do that for the first render, but only for subsequent renders.

**Comment by benoitjchevalier** [comment]
added some progressive rendering. Currently always rendering within 5 frames, we might want to add some logic to adjust the number of frames depending on the amount of data and/or if it's the first rendering
