### ISSUE TITLE
Tooltip

### ISSUE THREAD

**Issue by nonmetalhail** [PredixDev/px-vis-parallel-coordinates#2]
Explore tooltip integration options:
1) when under x series, we can use svg and then put a tooltip listener on each line; when over x series, no tooltip.
2) Use interaction space to get "closest" line to the cursor. Interaction space would have to go UNDER the axis drawing space to allow for axis drag and brush capabilities.

tooltip should display either point on the line at axis closest to the cursor or all axes values for that line

Need to see if either method is feasible performance  and interaction wise.

**Comment by benoitjchevalier** [comment]
After discussion with Jim the tooltip should show the 1 value for that tag (closest line). Possibly associated timestamp.

implementation suggestion:
-find closest tag to cursor
-find closest data (to cursor) for this tag 
might have to build a map [tag, [data point]]

**Comment by nonmetalhail** [comment]
complete in v0.1.15
