### ISSUE TITLE
Add register (and mute / unmute)

### ISSUE THREAD

**Issue by nonmetalhail** [PredixDev/px-vis-parallel-coordinates#3]
Need to add an optional register. It just needs to display the axis names, not any values. You should be able to mute an axis via the register and it will remove the corresponding axis from the chart. Unmuteing the axis via the register will then return it to the chart.

**Comment by nonmetalhail** [comment]
mute / unmute now working; register still needs to be done

**Comment by benoitjchevalier** [comment]
Fixed with 1.0.0 release
