### ISSUE TITLE
Add Chart Extents functionality

### ISSUE THREAD

**Issue by anundinesh** [PredixDev/px-vis-parallel-coordinates#33]
Hi, 
We tried passing chart-extents="{"x": [0,100],"y": [5,50]}" in the px-vis-parallel-coordinates, however we are not able to see any changes in the output. Could you please confirm whether this functionality will work in this component?

Also, confirm is it "dynaimc" or "dynamic"? as per specification it is like below.
chartExtents
Object notifies
Developer set chart extents for the chart. The chart will draw to whatever values are specified in the chartExtents.

 {
     "x": [0,100],
     "y": [5,50],
 }
To force the chart to calculate based on data, use "dynamic".

 {
     "x": [0,"dynaimc"],
     "y": [-10,"dynaimc"],
 }
For an ordinal dataset, chart extents can be set like this:

 {
     "x": ['low','medium','high'],
     "y": [5,50],
 }

**Comment by nonmetalhail** [comment]
No, parallel does not support this property. I see it is listed in the docs and will fix that. 

We probably should support it for consistency with our other charts, but in that case, you would have to provide a chart extent for every axis, so I dont know if it is worth it.
