### ISSUE TITLE
Thickness of axis on Safari 9 is thicker than other browsers

### ISSUE THREAD

**Issue by vonsichart200** [PredixDev/px-vis-parallel-coordinates#35]
Thickness of axis on Safari 9 is thicker than other browsers. And renders differently on different displays.

(See Wade for details.)

**Comment by nonmetalhail** [comment]
Browser bug. Cannot fix. Might want to try to open a bug on Safari if that is possible.

**Comment by randyaskin** [comment]
With release of Safari 11 last month, we only need to support Safari 10 & 11.
