### ISSUE TITLE
enable multiple categories

### ISSUE THREAD

**Issue by nonmetalhail** [PredixDev/px-vis-parallel-coordinates#8]
We need to support multiple categories (assets) where each set of lines get a different color based on category.

**Comment by nonmetalhail** [comment]
This needs to be further defined. Let's put this on hold until we can talk with Rob

**Comment by nonmetalhail** [comment]
Support added; still need to consult Design regarding how it appears on register since spec doesnt work

**Comment by benoitjchevalier** [comment]
Categories are related to assets rather than tags. We only need to provide ability for people to pass in a category with each asset

**Comment by nonmetalhail** [comment]
That was my understanding as well and that is what I implemented. Still need to speak with Rob about how this integrates with register as his specs do not demonstrate that.
